import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../myComponents/Navbar";
import Footer from "@/myComponents/Footer";
import BreadCrumb from "@/myComponents/BreadCrumb";
import ToastContext from "@/myComponents/ToastContext";
import AuthProvider from "@/components/AuthProvider";

export const metadata: Metadata = {
  title: "Clicon e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastContext />
          <Navbar />
          {/* breadCrumbs */}
          {/* <BreadCrumb /> */}
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
