import AccountSidebar from "@/myComponents/AccountSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Account",
  description: "Generated by create next app",
};

export default async function AccountLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="py-10 px-6">
      <section className="w-full max-w-[1100px] mx-auto  px-4 flex gap-5">
        {/* left bar */}
        <AccountSidebar />

        {/* right content */}
        <section className="flex-1">{children}</section>
      </section>
    </section>
  );
}
